version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.dev
      args:
        - ports=8080
        - DOCKER_BUILDKIT=1
    environment:
      MOOC_HOST: 0.0.0.0
    volumes:
     - ./migrations:/migrations
    ports:
      - 8080:8080
      - 4000:4000
      - 2345:2345
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0.22
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: codely
      MYSQL_USER: codely
      MYSQL_PASSWORD: codely
      MYSQL_ROOT_PASSWORD: codely
    expose:
      - 3306
  
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:8.0.29
    container_name: MySQL-Workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - mysql-workbench-data:/config
    ports:
      - 5014:3000
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
    
volumes:
  mysql_data:
  mysql-workbench-data: