version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.debug
      args:
        - ports=8080
    environment:
      MOOC_HOST: 0.0.0.0
    ports:
      - 8080:8080
      - 2345:2345
      